# -*- coding: utf-8 -*-
"""파이썬3장.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K2B-aEuLBDuSP_FhQ2eGUBeqm8y72hrf
"""

while True:
  print('\n1. 새로 만들기')
  print('2. 메모 보기')
  print('3. 메모 추가하기\n')
  i = int(input('명령을 선택하세요(종료 : 0)>>'))
  if i==0:
    print('프로그램을 종료합니다.')
    break
  if i==1:
    print('새로운 메모장을 생성합니다.')
    str = input('메모 입력:')
    with open('test.txt', 'w') as f:
      f.write(str)
  if i==2:
    print('메모장의 내용을 출력합니다.')
    print('==========메모==========')
    with open('test.txt', 'r') as f:
      print(f.read())
    print('========================')    
  if i==3:
    print('기존 메모장에 내용을 추가합니다.')
    str = input('추가 사항 입력:')
    with open('test.txt', 'a') as f:
      f.write('\n' + str)