# -*- coding: utf-8 -*-
"""파이썬2장.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O98-Lr1-qNOHID2aPkIfQoa4Bqn1ULFJ
"""

x = [1,2,3,4,5,6]
print(x)

for x in [1,2,3,4]:
  print(x)
print(x+x)

x = 7
if x%7==0:
  print(x,"는 7의 배수입니다.")

for x in range(10):
  print(x)

for x in range(1,101):
  if x%7==0:
    print(x,"는 7의 배수입니다.")

x = round((50 + 45 + 33 + 39 + 29 + 30) / 6, 1)
print(x)

import math
math.ceil(567/7)
#math.floor(567/7)

c = 29
f = (c - 32) * 5 / 9
#print(f)
print(f"섭씨 {c} 도는 화씨 {f:.2f} 도입니다.")

for i in range(2,20):
  for j in range(2,20):
    print(f"{i}X{j}={i*j}")

a = input('떡볶이는 몇 그릇 팔았나요?')
b = input('라면은 몇 그릇 팔았나요?')
c = input('튀김은 몇 개 팔았나요?')
print('-----<오늘의 매출 정산>-----')
print('떡볶이의 매출: %d원' %(int(a) * 2000))
print('라면의 매출: %d원' %(int(b) * 3000))
print('튀김의 매출: %d원' %(int(c) * 500))
print('오늘의 총 매출은 %d원입니다' %(int(a)*2000 + int(b)*3000 + int(c)*500))

money = input('투입한 돈은?')
a = input('1구간 표의 수는?')
b = input('2구간 표의 수는?')
change = int(money) - (int(a)*1300 + int(b)*1500)
print('잔돈: %d 원' %int(change))
print('1000원 지폐: %d 장' %(change // 1000))
print('100원 동전: %d 개' %(change % 1000 // 100))

def service_price():
  i = input('서비스 종류를 입력하세요, a/b/c:')
  if i=='a':
    i = 23
  if i=='b':
    i = 40
  if i=='c':
    i = 67
  j = input('부사게를 포함합니까? y/n:')
  if j=='y':
    i *= 1.1
  print(f"{i}만 원입니다")
service_price()

print(14 % 4)

round(1.12345, 2)

a = input('나이를 입력하세요: ')
print(40 - int(a))

plus = lambda x, y : x + y
print(plus(34,54))

def mean(a,b):
  return (a + b) / 2

print(mean(33,22))
print(45 + mean(33,22))

b = [1,2,3,10,11,12]
for i in b:
  if i < 10:
    print(i)
  else:
    print(i-10)

